### ISSUE TITLE
pip build is lagging behind current commit

### ISSUE THREAD

**Issue by JulianSpagnuolo** [jiangdada1221/TCR2vec#1]
Hi, thanks for the tool and making it available to evaluate. 

I was going to check some embeddings on some in house data however your utility script "cdr2full" isn't installed in the current pip build.

`ImportError: cannot import name 'cdr2full' from 'tcr2vec.utils'`

**Comment by jiangdada1221** [comment]
Sorry for the inconvenience. 
Sometimes I will make some updates and thus the PyPI package will be behind the current version. A better way to install the package is through git clone: git clone https://github.com/jiangdada1221/TCR2vec.git; cd TCR2vec; pip install .; 

Btw, a new version of TCR2vec trained on TCRdb [Chen et al. 2021] is available at [this link](https://drive.google.com/file/d/1CeF701iHVfWHbffG7eib9EGE8rbCcm3f/view?usp=sharing). Perhaps you can try both models.

**Comment by JulianSpagnuolo** [comment]
thanks!
